language: java
os: linux
jdk: openjdk8
addons:
  sonarcloud:
    organization: theodor1289
    token:
      secure: VcdPCtf2cdaokZ82LOkilnxmooEOx3gu3s5I3um/Imz+EAl/IS2RzA4hRM8ZNsm/8iarrC9M2Ipw8l2T0NYpShpmfliXYjXaleY81Dq9RByvLO4PwzwbkxvVWSZPS8SpeQ0Yre/J8NOxh6HEo0k+EJH/Wje4Gn0eixco8lsZdecni6BNveFVVV2zD7F7kvVo7tYHvED8MlizxhxttJlXQfl8jvjw5YYlk9nLogp4uoPQquMn0xk7lWYCpZFY2slpQV4JD3He3bEPEZZSQQPggIj0V4nVhOPt1EoUmpB7is9SLjint8vVDK3y58TXBMGdk+hh+Qv2AY82UsuI/zezXGOB+fGNYqNvXPoopYNvEZ9ALWfMJcO2NtCjYLi59zqJObyIQnO6DqcKEPzpcUxfZNMEGzAcegFqpemIxy0AX3Oecpobyb/0TJocR5aSax980hKmbsgAgPaKV7SW1YdYBvxJb+4APRDStScz7CoqQpKrNeH9gRFfRAzGtfxzTLTJo2YSFCFo4LKr4aoJ+Cb1a1YdIRocUC2eIEI/YzI8Rmxl06scne+LYkACbJbRAJlDW4ta2DUFNRCyXvLRKjJsASrmIH5ZgDJULmVoofLvkLTOiIwuxAlFqmlpiZINeItdmkgEKv7mESzQFNE1HBAk112utR51NiNqq4inD+1+TDM=
before_script: cd server
script:
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: weather-match
  cleanup: false
before_install:
- openssl aes-256-cbc -K $encrypted_239dbd766207_key -iv $encrypted_239dbd766207_iv
  -in server/src/main/resources/application.properties.enc -out server/src/main/resources/application.properties -d
